/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.0.27
 * Generated at: 2024-05-16 15:04:52 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import modelClass.AdminUpdate;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.Connection;
import dpConnection.DpConnection;
import modelClass.Login;

public final class adminInsertDataPage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.sql.Connection");
    _jspx_imports_classes.add("modelClass.Login");
    _jspx_imports_classes.add("modelClass.AdminUpdate");
    _jspx_imports_classes.add("java.sql.ResultSet");
    _jspx_imports_classes.add("java.sql.Statement");
    _jspx_imports_classes.add("dpConnection.DpConnection");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<title>Update Form</title>\n");
      out.write("<link rel=\"stylesheet\" href=\"./css/bootstrap.min.css\">\n");
      out.write("<link rel=\"stylesheet\" href=\"./registration.css\">\n");
      out.write("<link rel=\"stylesheet\"\n");
      out.write("	href=\"https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css\">\n");
      out.write("\n");
      out.write("<style>\n");
      out.write("body {\n");
      out.write("	height: 100vh;\n");
      out.write("	width: 100vw;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".datas {\n");
      out.write("	display: flex;\n");
      out.write("	width: 100%;\n");
      out.write("	height: 100%;\n");
      out.write("	margin-left: 100px;\n");
      out.write("	content: normal;\n");
      out.write("	overflow: auto;\n");
      out.write("	margin-left: 100px;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".datas1 {\n");
      out.write("	width: 50%;\n");
      out.write("	overflow: auto;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".allinputs {\n");
      out.write("	width: 80%;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".datas2 {\n");
      out.write("	height: auto;\n");
      out.write("	width: 50%;\n");
      out.write("	overflow: auto;\n");
      out.write("	width: 50%;\n");
      out.write("}\n");
      out.write("</style>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("\n");
      out.write("	");

	Login authentication = (Login) session.getAttribute("userEmail");
	if (authentication == null) {
		response.sendRedirect("login.jsp");
	}
	
	Connection con = DpConnection.getConnection();
	Statement stm = con.createStatement();
	ResultSet rs = stm.executeQuery("select * from airlineRegistration");
	
      out.write("\n");
      out.write("	<div class=\"datas\">\n");
      out.write("		<div class=\"datas1\">\n");
      out.write("			<div class=\"container card allinputs\">\n");
      out.write("				<h1>Add User </h1>\n");
      out.write("				<form action=\"adminAddDataServlet\" class=\"needs-validation\"\n");
      out.write("					method=\"post\">\n");
      out.write("					<div class=\"form-group\">\n");
      out.write("						<label for=\"validationServer10\">id</label> <input type=\"number\"\n");
      out.write("							class=\"form-control\" id=\"validationServer10\" name=\"id\"\n");
      out.write("							\n");
      out.write("						readonly=\"readonly\"	required>\n");
      out.write("\n");
      out.write("					</div>\n");
      out.write("					<div class=\"form-group\">\n");
      out.write("						<label for=\"validationServer01\">First Name</label> <input\n");
      out.write("							type=\"text\" class=\"form-control\" id=\"validationServer01\"\n");
      out.write("							name=\"fName\"\n");
      out.write("							required autofocus>\n");
      out.write("						<div class=\"valid-feedback\">Looks good!</div>\n");
      out.write("						<div class=\"invalid-feedback\">Please choose a FistName.</div>\n");
      out.write("					</div>\n");
      out.write("					<div class=\"form-group\">\n");
      out.write("						<label for=\"validationServer02\">LastName</label> <input\n");
      out.write("							type=\"text\" class=\"form-control\" id=\"validationServer02\"\n");
      out.write("							name=\"lName\"\n");
      out.write("							required autofocus>\n");
      out.write("						<div class=\"valid-feedback\">Looks good!</div>\n");
      out.write("						<div class=\"invalid-feedback\">Please choose a LastName.</div>\n");
      out.write("					</div>\n");
      out.write("					<div class=\"form-group\">\n");
      out.write("						<label for=\"validationServer03\">Username</label> <input\n");
      out.write("							type=\"text\" class=\"form-control\" id=\"validationServer03\"\n");
      out.write("							name=\"userName\"\n");
      out.write("							required>\n");
      out.write("						<div class=\"valid-feedback\">Looks good!</div>\n");
      out.write("						<div class=\"invalid-feedback\">Please choose a username.</div>\n");
      out.write("					</div>\n");
      out.write("					<div class=\"form-group\">\n");
      out.write("						<label for=\"validationServer04\">Password</label> <input\n");
      out.write("							type=\"password\" class=\"form-control\" id=\"validationServer04\"\n");
      out.write("							name=\"password\"\n");
      out.write("							required>\n");
      out.write("						<div class=\"valid-feedback\">Looks good!</div>\n");
      out.write("						<div class=\"invalid-feedback\">Please enter a password.</div>\n");
      out.write("					</div>\n");
      out.write("					<div class=\"form-group\">\n");
      out.write("						<label for=\"validationServer012\">Email</label> <input type=\"email\"\n");
      out.write("							class=\"form-control\" id=\"validationServer04\" name=\"email\"\n");
      out.write("							required>\n");
      out.write("						<div class=\"valid-feedback\">Looks good!</div>\n");
      out.write("						<div class=\"invalid-feedback\">Please choose a email.</div>\n");
      out.write("					</div>\n");
      out.write("					<div class=\"form-group\">\n");
      out.write("						<label for=\"validationServer04\">DOB</label> <input type=\"date\"\n");
      out.write("							class=\"form-control\" id=\"validationServer04\" name=\"dob\"\n");
      out.write("							required>\n");
      out.write("						<div class=\"valid-feedback\">Looks good!</div>\n");
      out.write("						<div class=\"invalid-feedback\">Please choose a DOB.</div>\n");
      out.write("					</div>\n");
      out.write("					<div class=\"form-group\">\n");
      out.write("						<label for=\"validationServer05\">Age</label> <input type=\"number\"\n");
      out.write("							class=\"form-control\" id=\"validationServer05\" name=\"age\"\n");
      out.write("							required>\n");
      out.write("						<div class=\"valid-feedback\">Looks good!</div>\n");
      out.write("						<div class=\"invalid-feedback\">Please choose a Age.</div>\n");
      out.write("					</div>\n");
      out.write("					<div class=\"form-group Gender\">\n");
      out.write("						<label for=\"Male\">Gender</label> <input type=\"radio\" id=\"Male\"\n");
      out.write("							name=\"Gender\" value=\"Male\"\n");
      out.write("							checked required> <label for=\"Male\">Male</label> <input\n");
      out.write("							type=\"radio\" id=\"Female\" name=\"Gender\" value=\"Female\"\n");
      out.write("							required> <label for=\"Female\">Female</label>\n");
      out.write("\n");
      out.write("					</div>\n");
      out.write("					<div class=\"form-group\">\n");
      out.write("						<label for=\"validationServer07\">MobileNumber</label> <input\n");
      out.write("							type=\"tel\" class=\"form-control\" id=\"validationServer07\"\n");
      out.write("							name=\"mobileNumber\" pattern=\"[0-9]{10}\"\n");
      out.write("							required>\n");
      out.write("						<div class=\"valid-feedback\">Looks good!</div>\n");
      out.write("						<div class=\"invalid-feedback\">Please choose a MobileNumber.</div>\n");
      out.write("					</div>\n");
      out.write("					<div class=\"form-group\">\n");
      out.write("						<label for=\"validationServer08\">Address</label> <input type=\"text\"\n");
      out.write("							class=\"form-control\" id=\"validationServer08\" name=\"address\"\n");
      out.write("							required>\n");
      out.write("						<div class=\"valid-feedback\">Looks good!</div>\n");
      out.write("						<div class=\"invalid-feedback\">Please choose a Address.</div>\n");
      out.write("					</div>\n");
      out.write("					<div class=\"form-group\">\n");
      out.write("						<label for=\"validationServer09\">City</label> <input type=\"text\"\n");
      out.write("							class=\"form-control\" id=\"validationServer09\" name=\"city\"\n");
      out.write("							required>\n");
      out.write("						<div class=\"valid-feedback\">Looks good!</div>\n");
      out.write("						<div class=\"invalid-feedback\">Please choose a City.</div>\n");
      out.write("					</div>\n");
      out.write("					<div class=\"form-group\">\n");
      out.write("						<label for=\"validationServer10\">State</label> <input type=\"text\"\n");
      out.write("							class=\"form-control\" id=\"validationServer10\" name=\"state\"\n");
      out.write("							required>\n");
      out.write("						<div class=\"valid-feedback\">Looks good!</div>\n");
      out.write("						<div class=\"invalid-feedback\">Please choose a State.</div>\n");
      out.write("					</div>\n");
      out.write("					<div class=\"form-group\">\n");
      out.write("						<label for=\"validationServer11\">Pincode</label> <input type=\"number\"\n");
      out.write("							class=\"form-control\" id=\"validationServer11\" name=\"pincode\"\n");
      out.write("							required>\n");
      out.write("						<div class=\"valid-feedback\">Looks good!</div>\n");
      out.write("						<div class=\"invalid-feedback\">Please choose a Pincode.</div>\n");
      out.write("					</div>\n");
      out.write("\n");
      out.write("					<button class=\"mt-5 mb-2 pr-2 btn btn-primary\" type=\"submit\">Add</button>\n");
      out.write("					<a href=\"adminPage.jsp\" class=\"mt-5 mb-2  btn btn-primary\">Home</a>\n");
      out.write("				</form>\n");
      out.write("			</div>\n");
      out.write("		</div>\n");
      out.write("\n");
      out.write("		<div class=\"datas2\">\n");
      out.write("			<div class=\"col\">\n");
      out.write("				<div class=\"table-wrapper\">\n");
      out.write("					<table class=\"table table-bordered\">\n");
      out.write("						<thead>\n");
      out.write("							<th>\n");
      out.write("							<tr>\n");
      out.write("								<th>id</th>\n");
      out.write("								<th>First Name</th>\n");
      out.write("								<th>Last Name</th>\n");
      out.write("								<th>user Name</th>\n");
      out.write("								<th>Password</th>\n");
      out.write("								<th>Email</th>\n");
      out.write("								<th>DOB</th>\n");
      out.write("								<th>Age</th>\n");
      out.write("								<th>Gender</th>\n");
      out.write("								<th>Mobile Number</th>\n");
      out.write("								<th>Address</th>\n");
      out.write("								<th>city</th>\n");
      out.write("								<th>State</th>\n");
      out.write("								<th>Pincode</th>\n");
      out.write("							</tr>\n");
      out.write("							</th>\n");
      out.write("						</thead>\n");
      out.write("						<tbody>\n");
      out.write("\n");
      out.write("							");

							while (rs.next()) {
							
      out.write("\n");
      out.write("\n");
      out.write("							<tr>\n");
      out.write("								<td>");
      out.print(rs.getInt("id"));
      out.write("</td>\n");
      out.write("								<td>");
      out.print(rs.getString("FirstName"));
      out.write("</td>\n");
      out.write("								<td>");
      out.print(rs.getString("LastName"));
      out.write("</td>\n");
      out.write("								<td>");
      out.print(rs.getString("UserName"));
      out.write("</td>\n");
      out.write("								<td>");
      out.print(rs.getString("Password"));
      out.write("</td>\n");
      out.write("								<td>");
      out.print(rs.getString("Email"));
      out.write("</td>\n");
      out.write("								<td>");
      out.print(rs.getString("DOB"));
      out.write("</td>\n");
      out.write("								<td>");
      out.print(rs.getInt("Age"));
      out.write("</td>\n");
      out.write("								<td>");
      out.print(rs.getString("Gender"));
      out.write("</td>\n");
      out.write("								<td>");
      out.print(rs.getLong("MobileNumber"));
      out.write("</td>\n");
      out.write("								<td>");
      out.print(rs.getString("Address"));
      out.write("</td>\n");
      out.write("								<td>");
      out.print(rs.getString("City"));
      out.write("</td>\n");
      out.write("								<td>");
      out.print(rs.getString("State"));
      out.write("</td>\n");
      out.write("								<td>");
      out.print(rs.getLong("PinCode"));
      out.write("</td>\n");
      out.write("							</tr>\n");
      out.write("\n");
      out.write("							");

							}
							
      out.write("\n");
      out.write("						</tbody>\n");
      out.write("					</table>\n");
      out.write("				</div>\n");
      out.write("			</div>\n");
      out.write("		</div>\n");
      out.write("	</div>\n");
      out.write("\n");
      out.write("	<!-- Bootstrap JS (optional if you have JavaScript features) -->\n");
      out.write("	<script src=\"/w3School/airline/js/bootstrap.min.js\"></script>\n");
      out.write("	<script>\n");
      out.write("		document.addEventListener(\"DOMContentLoaded\", function() {\n");
      out.write("			// Get all input fields that require dynamic validation\n");
      out.write("			const inputFields = document.querySelectorAll('.form-control');\n");
      out.write("\n");
      out.write("			// Add event listener for input event to each input field\n");
      out.write("			inputFields.forEach(function(inputField) {\n");
      out.write("				inputField.addEventListener('input', function(event) {\n");
      out.write("					// Check if the input field is valid\n");
      out.write("					if (inputField.validity.valid) {\n");
      out.write("						// Add the 'is-valid' class\n");
      out.write("						inputField.classList.add('is-valid');\n");
      out.write("						// Remove the 'is-invalid' class if present\n");
      out.write("						inputField.classList.remove('is-invalid');\n");
      out.write("					} else {\n");
      out.write("						// Add the 'is-invalid' class\n");
      out.write("						inputField.classList.add('is-invalid');\n");
      out.write("						// Remove the 'is-valid' class if present\n");
      out.write("						inputField.classList.remove('is-valid');\n");
      out.write("					}\n");
      out.write("				});\n");
      out.write("			});\n");
      out.write("\n");
      out.write("			// Add event listener for form submission\n");
      out.write("			document.querySelector('form').addEventListener('submit',\n");
      out.write("					function(event) {\n");
      out.write("						// Prevent form submission if any input field is invalid\n");
      out.write("						if (!this.checkValidity()) {\n");
      out.write("							event.preventDefault();\n");
      out.write("							event.stopPropagation();\n");
      out.write("						}\n");
      out.write("\n");
      out.write("						// Add 'was-validated' class to show validation styles\n");
      out.write("						this.classList.add('was-validated');\n");
      out.write("					});\n");
      out.write("		});\n");
      out.write("	</script>\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
