/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.0.27
 * Generated at: 2024-05-16 16:33:21 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class registration_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("<head>\n");
      out.write("    <meta charset=\"UTF-8\">\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("    <title>Registration</title>\n");
      out.write("    <!-- Bootstrap CSS -->\n");
      out.write("    <link rel=\"stylesheet\" href=\"./css/bootstrap.min.css\">\n");
      out.write("    <link rel=\"stylesheet\" href=\"./registration.css\">\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("<div class=\"container card allinputs\">\n");
      out.write("    <h1>Registration Form</h1>\n");
      out.write("    <form action=\"RegistrationServlet\" class=\"needs-validation\" method=\"post\">\n");
      out.write("        <div class=\"form-group\">\n");
      out.write("            <label for=\"validationServer01\">First</label>\n");
      out.write("            <input type=\"text\" class=\"form-control\" id=\"validationServer01\" name=\"fName\" required autofocus>\n");
      out.write("            <div class=\"valid-feedback\">\n");
      out.write("                Looks good!\n");
      out.write("            </div>\n");
      out.write("            <div class=\"invalid-feedback\">\n");
      out.write("                Please choose a FistName.\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"form-group\">\n");
      out.write("            <label for=\"validationServer02\">LastName</label>\n");
      out.write("            <input type=\"text\" class=\"form-control\" id=\"validationServer02\" name=\"lName\" required autofocus>\n");
      out.write("            <div class=\"valid-feedback\">\n");
      out.write("                Looks good!\n");
      out.write("            </div>\n");
      out.write("            <div class=\"invalid-feedback\">\n");
      out.write("                Please choose a LastName.\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"form-group\">\n");
      out.write("            <label for=\"validationServer03\">Username</label>\n");
      out.write("            <input type=\"text\" class=\"form-control\" id=\"validationServer03\" name=\"userName\" required>\n");
      out.write("            <div class=\"valid-feedback\">\n");
      out.write("                Looks good!\n");
      out.write("            </div>\n");
      out.write("            <div class=\"invalid-feedback\">\n");
      out.write("                Please choose a username.\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"form-group\">\n");
      out.write("            <label for=\"validationServer04\">Password</label>\n");
      out.write("            <input type=\"password\" class=\"form-control\" id=\"validationServer04\" name=\"password\" required>\n");
      out.write("            <div class=\"valid-feedback\">\n");
      out.write("                Looks good!\n");
      out.write("            </div>\n");
      out.write("            <div class=\"invalid-feedback\">\n");
      out.write("                Please enter a password.\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"form-group\">\n");
      out.write("            <label for=\"validationServer012\">Email</label>\n");
      out.write("            <input type=\"email\" class=\"form-control\" id=\"validationServer04\" name=\"email\" required>\n");
      out.write("            <div class=\"valid-feedback\">\n");
      out.write("                Looks good!\n");
      out.write("            </div>\n");
      out.write("            <div class=\"invalid-feedback\">\n");
      out.write("                Please choose a email.\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"form-group\">\n");
      out.write("            <label for=\"validationServer04\">DOB</label>\n");
      out.write("            <input type=\"date\" class=\"form-control\" id=\"validationServer04\" name=\"dob\" required>\n");
      out.write("            <div class=\"valid-feedback\">\n");
      out.write("                Looks good!\n");
      out.write("            </div>\n");
      out.write("            <div class=\"invalid-feedback\">\n");
      out.write("                Please choose a DOB.\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"form-group\">\n");
      out.write("            <label for=\"validationServer05\">Age</label>\n");
      out.write("            <input type=\"number\" class=\"form-control\" id=\"validationServer05\" name=\"age\" required>\n");
      out.write("            <div class=\"valid-feedback\">\n");
      out.write("                Looks good!\n");
      out.write("            </div>\n");
      out.write("            <div class=\"invalid-feedback\">\n");
      out.write("                Please choose a Age.\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"form-group Gender\">\n");
      out.write("            <label for=\"Male\">Gender</label>\n");
      out.write("            <input type=\"radio\"  id=\"Male\" name=\"Gender\" value=\"Male\" checked required>\n");
      out.write("            <label for=\"Male\">Male</label>\n");
      out.write("            <input type=\"radio\"  id=\"Female\" name=\"Gender\" value=\"Female\" required>\n");
      out.write("            <label for=\"Female\">Female</label>\n");
      out.write("\n");
      out.write("        </div>\n");
      out.write("        <div class=\"form-group\">\n");
      out.write("            <label for=\"validationServer07\">MobileNumber</label>\n");
      out.write("            <input type=\"tel\" class=\"form-control\" id=\"validationServer07\" name=\"mobileNumber\" pattern=\"[0-9]{10}\" required>\n");
      out.write("            <div class=\"valid-feedback\">\n");
      out.write("                Looks good!\n");
      out.write("            </div>\n");
      out.write("            <div class=\"invalid-feedback\">\n");
      out.write("                Please choose a MobileNumber.\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"form-group\">\n");
      out.write("            <label for=\"validationServer08\">Address</label>\n");
      out.write("            <input type=\"text\" class=\"form-control\" id=\"validationServer08\" name=\"address\" required>\n");
      out.write("            <div class=\"valid-feedback\">\n");
      out.write("                Looks good!\n");
      out.write("            </div>\n");
      out.write("            <div class=\"invalid-feedback\">\n");
      out.write("                Please choose a Address.\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"form-group\">\n");
      out.write("            <label for=\"validationServer09\">City</label>\n");
      out.write("            <input type=\"text\" class=\"form-control\" id=\"validationServer09\" name=\"city\" required>\n");
      out.write("            <div class=\"valid-feedback\">\n");
      out.write("                Looks good!\n");
      out.write("            </div>\n");
      out.write("            <div class=\"invalid-feedback\">\n");
      out.write("                Please choose a City.\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"form-group\">\n");
      out.write("            <label for=\"validationServer10\">State</label>\n");
      out.write("            <input type=\"text\" class=\"form-control\" id=\"validationServer10\" name=\"state\" required>\n");
      out.write("            <div class=\"valid-feedback\">\n");
      out.write("                Looks good!\n");
      out.write("            </div>\n");
      out.write("            <div class=\"invalid-feedback\">\n");
      out.write("                Please choose a State.\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"form-group\">\n");
      out.write("            <label for=\"validationServer11\">Pincode</label>\n");
      out.write("            <input type=\"number\" class=\"form-control\" id=\"validationServer11\" name=\"pincode\" required>\n");
      out.write("            <div class=\"valid-feedback\">\n");
      out.write("                Looks good!\n");
      out.write("            </div>\n");
      out.write("            <div class=\"invalid-feedback\">\n");
      out.write("                Please choose a Pincode.\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"col-12\">\n");
      out.write("            <div class=\"form-check\">\n");
      out.write("              <input class=\"form-check-input\" type=\"checkbox\" value=\"\" id=\"invalidCheck\" required>\n");
      out.write("              <label class=\"form-check-label\" for=\"invalidCheck\">\n");
      out.write("                Agree to terms and conditions\n");
      out.write("              </label>\n");
      out.write("              <div class=\"invalid-feedback\">\n");
      out.write("                You must agree before submitting.\n");
      out.write("              </div>\n");
      out.write("            </div>\n");
      out.write("          </div>\n");
      out.write("        <button class=\"btn btn-primary\" type=\"submit\">Submit</button>\n");
      out.write("    </form>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("<!-- Bootstrap JS (optional if you have JavaScript features) -->\n");
      out.write("<script src=\"/w3School/airline/js/bootstrap.min.js\"></script>\n");
      out.write("\n");
      out.write("<script>\n");
      out.write("    document.addEventListener(\"DOMContentLoaded\", function() {\n");
      out.write("        // Get all input fields that require dynamic validation\n");
      out.write("        const inputFields = document.querySelectorAll('.form-control');\n");
      out.write("\n");
      out.write("        // Add event listener for input event to each input field\n");
      out.write("        inputFields.forEach(function(inputField) {\n");
      out.write("            inputField.addEventListener('input', function(event) {\n");
      out.write("                // Check if the input field is valid\n");
      out.write("                if (inputField.validity.valid) {\n");
      out.write("                    // Add the 'is-valid' class\n");
      out.write("                    inputField.classList.add('is-valid');\n");
      out.write("                    // Remove the 'is-invalid' class if present\n");
      out.write("                    inputField.classList.remove('is-invalid');\n");
      out.write("                } else {\n");
      out.write("                    // Add the 'is-invalid' class\n");
      out.write("                    inputField.classList.add('is-invalid');\n");
      out.write("                    // Remove the 'is-valid' class if present\n");
      out.write("                    inputField.classList.remove('is-valid');\n");
      out.write("                }\n");
      out.write("            });\n");
      out.write("        });\n");
      out.write("\n");
      out.write("        // Add event listener for form submission\n");
      out.write("        document.querySelector('form').addEventListener('submit', function(event) {\n");
      out.write("            // Prevent form submission if any input field is invalid\n");
      out.write("            if (!this.checkValidity()) {\n");
      out.write("                event.preventDefault();\n");
      out.write("                event.stopPropagation();\n");
      out.write("            }\n");
      out.write("\n");
      out.write("            // Add 'was-validated' class to show validation styles\n");
      out.write("            this.classList.add('was-validated');\n");
      out.write("        });\n");
      out.write("    });\n");
      out.write("</script>\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
